service: dan-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket:
    name: cohort5.deployment

functions:
  pranata:
    handler: index.pranata
    events:
      - httpApi: 
          path: /
          method: get

  pranatapost:
    handler: index.pranatapost
    events:
      - httpApi: 
          path: /post
          method: post
      - sqs: 
          arn: 
            Fn::GetAtt:
              - DanQueue
              - Arn

resources:
  Resources:
    DanQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "dan-queue"
          
plugins:
  - serverless-offline